# Generated by Django 3.2.6 on 2021-12-10 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movies_list',
            name='image',
            field=models.ImageField(default=3, max_length=2083, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies_list',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies_list',
            name='rating',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
