# Generated by Django 3.2.6 on 2021-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211210_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_list',
            name='rating',
            field=models.FloatField(),
        ),
    ]
