# Generated by Django 3.2.6 on 2021-10-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_text_contact_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nm',
        ),
    ]
